// =====================================================================
// Datos de muestra para previsualizar la interfaz sin un proyecto
// Supabase conectado todavía. Los ejercicios de muestra son reales
// (free-exercise-db, dominio público) con imágenes desde jsDelivr.
//
// Cuando conectes Supabase, reemplaza estas funciones por consultas:
//   const supabase = await createClient();
//   const { data } = await supabase.from("exercises").select("*");
// Las formas coinciden con src/lib/types/database.ts.
// =====================================================================

import type {
  ExerciseRow,
  RoutineRow,
  RoutineDayRow,
  RoutineExerciseRow,
  UserProfileRow,
  WorkoutSessionRow,
  BodyMetricRow,
  NutritionLogRow,
} from "@/lib/types/database";

export const mockProfile: UserProfileRow = {
  id: "p1",
  user_id: "u1",
  name: "Sofia",
  age: 27,
  gender: "femenino",
  height_cm: 165,
  current_weight_kg: 64.2,
  goal: "tonificar",
  level: "intermedio",
  training_days: 4,
  session_duration_minutes: 60,
  injuries: null,
  equipment_available: ["gimnasio_completo"],
  onboarding_completed: true,
  created_at: "2026-01-10T00:00:00Z",
  updated_at: "2026-06-20T00:00:00Z",
};

export const mockExercises: ExerciseRow[] = [
  {
    id: "e1",
    name: "Barbell Bench Press",
    slug: "barbell-bench-press-medium-grip",
    description: "Push movement, compound.",
    instructions: ["Lie on a flat bench and grip the bar slightly wider than shoulder width.","Lower the bar under control until it touches your chest, elbows slightly tucked.","Press the bar up to full extension, exhaling through the effort.","Repeat for the prescribed reps."],
    main_muscle: "pecho",
    secondary_muscles: ["hombros","triceps"],
    equipment: ["barras","gimnasio_completo"],
    difficulty: "intermedio",
    type: "fuerza",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Bench_Press_-_Medium_Grip/1.jpg"],
    force: "Empuje",
    mechanic: "Compuesto",
    common_mistakes: [],
    tips: [],
    recommended_sets: 4,
    recommended_reps: "6-10",
    recommended_rest_seconds: 120,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e2",
    name: "Standing Military Press",
    slug: "standing-military-press",
    description: "Push movement, compound.",
    instructions: ["Standing, hold the bar at shoulder height with hands just outside your shoulders.","Brace your core and glutes to stabilize your torso.","Press the bar overhead to full lockout.","Lower under control back to your shoulders and repeat."],
    main_muscle: "hombros",
    secondary_muscles: ["triceps"],
    equipment: ["barras","gimnasio_completo"],
    difficulty: "intermedio",
    type: "fuerza",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Standing_Military_Press/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Standing_Military_Press/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Standing_Military_Press/1.jpg"],
    force: "Empuje",
    mechanic: "Compuesto",
    common_mistakes: [],
    tips: [],
    recommended_sets: 4,
    recommended_reps: "6-10",
    recommended_rest_seconds: 120,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e3",
    name: "Triceps Pushdown",
    slug: "triceps-pushdown",
    description: "Push movement, isolation.",
    instructions: ["Grip the high-pulley bar at shoulder width.","Keep your elbows pinned to your sides throughout.","Push the bar down until your arms are fully extended.","Return under control without letting your elbows flare."],
    main_muscle: "triceps",
    secondary_muscles: [],
    equipment: ["maquinas","gimnasio_completo"],
    difficulty: "principiante",
    type: "fuerza",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Triceps_Pushdown/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Triceps_Pushdown/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Triceps_Pushdown/1.jpg"],
    force: "Empuje",
    mechanic: "Aislamiento",
    common_mistakes: [],
    tips: [],
    recommended_sets: 3,
    recommended_reps: "10-12",
    recommended_rest_seconds: 75,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e4",
    name: "Pull-ups",
    slug: "pullups",
    description: "Pull movement, compound.",
    instructions: ["Hang from the bar with a pronated, shoulder-width grip.","Squeeze your shoulder blades and pull until your chin clears the bar.","Lower under control to full extension.","Avoid swinging — keep every rep strict."],
    main_muscle: "espalda",
    secondary_muscles: ["biceps"],
    equipment: ["peso_corporal","gimnasio_completo"],
    difficulty: "avanzado",
    type: "fuerza",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Pullups/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Pullups/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Pullups/1.jpg"],
    force: "Tirón",
    mechanic: "Compuesto",
    common_mistakes: [],
    tips: [],
    recommended_sets: 4,
    recommended_reps: "6-10",
    recommended_rest_seconds: 120,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e5",
    name: "Bent-Over Barbell Row",
    slug: "bent-over-barbell-row",
    description: "Pull movement, compound.",
    instructions: ["Hinge forward with a flat back and soft knees.","Grip the bar pronated with arms extended.","Row the bar to your stomach, squeezing your shoulder blades.","Lower under control, keeping your back set."],
    main_muscle: "espalda",
    secondary_muscles: ["biceps","hombros"],
    equipment: ["barras","gimnasio_completo"],
    difficulty: "intermedio",
    type: "fuerza",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent_Over_Barbell_Row/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent_Over_Barbell_Row/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Bent_Over_Barbell_Row/1.jpg"],
    force: "Tirón",
    mechanic: "Compuesto",
    common_mistakes: [],
    tips: [],
    recommended_sets: 4,
    recommended_reps: "8-12",
    recommended_rest_seconds: 90,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e6",
    name: "Barbell Curl",
    slug: "barbell-curl",
    description: "Pull movement, isolation.",
    instructions: ["Standing, hold the bar with a supinated, shoulder-width grip.","Curl the bar toward your chest without moving your torso.","Squeeze your biceps at the top.","Lower under control to full extension."],
    main_muscle: "biceps",
    secondary_muscles: [],
    equipment: ["barras","mancuernas"],
    difficulty: "principiante",
    type: "fuerza",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Curl/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Curl/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Curl/1.jpg"],
    force: "Tirón",
    mechanic: "Aislamiento",
    common_mistakes: [],
    tips: [],
    recommended_sets: 3,
    recommended_reps: "10-12",
    recommended_rest_seconds: 75,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e7",
    name: "Barbell Full Squat",
    slug: "barbell-full-squat",
    description: "Push movement, compound.",
    instructions: ["Set the bar on your traps and stand shoulder-width apart.","Descend by bending hips and knees, chest up.","Go until your thighs are at least parallel to the floor.","Drive through your heels back to standing."],
    main_muscle: "piernas",
    secondary_muscles: ["gluteos","abdomen"],
    equipment: ["barras","gimnasio_completo"],
    difficulty: "intermedio",
    type: "fuerza",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Full_Squat/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Full_Squat/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Full_Squat/1.jpg"],
    force: "Empuje",
    mechanic: "Compuesto",
    common_mistakes: [],
    tips: [],
    recommended_sets: 4,
    recommended_reps: "6-10",
    recommended_rest_seconds: 150,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e8",
    name: "Romanian Deadlift",
    slug: "romanian-deadlift",
    description: "Pull movement, compound.",
    instructions: ["Hold the bar in front of your thighs with nearly straight legs.","Push your hips back, sliding the bar down your legs.","Lower until you feel a hamstring stretch, back flat.","Return by extending your hips and squeezing your glutes."],
    main_muscle: "piernas",
    secondary_muscles: ["gluteos","espalda"],
    equipment: ["barras","gimnasio_completo"],
    difficulty: "intermedio",
    type: "fuerza",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Romanian_Deadlift/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Romanian_Deadlift/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Romanian_Deadlift/1.jpg"],
    force: "Tirón",
    mechanic: "Compuesto",
    common_mistakes: [],
    tips: [],
    recommended_sets: 4,
    recommended_reps: "8-12",
    recommended_rest_seconds: 120,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e9",
    name: "Barbell Hip Thrust",
    slug: "barbell-hip-thrust",
    description: "Push movement, isolation.",
    instructions: ["Rest your upper back on a bench with the bar over your hips.","Drive your hips up to full extension.","Squeeze your glutes hard at the top.","Lower under control without fully resting."],
    main_muscle: "gluteos",
    secondary_muscles: ["piernas"],
    equipment: ["barras","gimnasio_completo"],
    difficulty: "principiante",
    type: "hipertrofia",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Hip_Thrust/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Hip_Thrust/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Hip_Thrust/1.jpg"],
    force: "Empuje",
    mechanic: "Aislamiento",
    common_mistakes: [],
    tips: [],
    recommended_sets: 4,
    recommended_reps: "10-15",
    recommended_rest_seconds: 90,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e10",
    name: "Dumbbell Lunges",
    slug: "dumbbell-lunges",
    description: "Push movement, compound.",
    instructions: ["Hold a dumbbell in each hand at your sides.","Take a long step forward, bending both knees to 90 degrees.","Push through your front heel to return to standing.","Alternate legs, keeping your torso upright."],
    main_muscle: "piernas",
    secondary_muscles: ["gluteos"],
    equipment: ["mancuernas","casa"],
    difficulty: "principiante",
    type: "hipertrofia",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Lunges/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Lunges/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Lunges/1.jpg"],
    force: "Empuje",
    mechanic: "Compuesto",
    common_mistakes: [],
    tips: [],
    recommended_sets: 3,
    recommended_reps: "10-12",
    recommended_rest_seconds: 75,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e11",
    name: "Plank",
    slug: "plank",
    description: "Static hold, isolation.",
    instructions: ["Support yourself on your forearms and toes.","Keep a straight line from head to heels.","Brace your core and glutes; don't let your hips sag.","Hold the position with controlled breathing."],
    main_muscle: "abdomen",
    secondary_muscles: ["espalda"],
    equipment: ["peso_corporal","casa"],
    difficulty: "principiante",
    type: "movilidad",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Plank/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Plank/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Plank/1.jpg"],
    force: "Estático",
    mechanic: "Aislamiento",
    common_mistakes: [],
    tips: [],
    recommended_sets: 3,
    recommended_reps: "30-60 seg",
    recommended_rest_seconds: 45,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e12",
    name: "Dumbbell Bench Press",
    slug: "dumbbell-bench-press",
    description: "Push movement, compound.",
    instructions: ["Lie on a bench with a dumbbell in each hand at chest level.","Press both dumbbells up without letting them touch.","Lower under control until you feel a chest stretch.","Repeat, squeezing your chest on every press."],
    main_muscle: "pecho",
    secondary_muscles: ["hombros","triceps"],
    equipment: ["mancuernas"],
    difficulty: "principiante",
    type: "hipertrofia",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bench_Press/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bench_Press/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Dumbbell_Bench_Press/1.jpg"],
    force: "Empuje",
    mechanic: "Compuesto",
    common_mistakes: [],
    tips: [],
    recommended_sets: 4,
    recommended_reps: "8-12",
    recommended_rest_seconds: 90,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e13",
    name: "Wide-Grip Lat Pulldown",
    slug: "wide-grip-lat-pulldown",
    description: "Pull movement, compound.",
    instructions: ["Sit down and take a wide grip on the bar.","Pull the bar to your upper chest, driving your elbows down.","Squeeze your shoulder blades at the bottom.","Return to the start under control."],
    main_muscle: "espalda",
    secondary_muscles: ["biceps"],
    equipment: ["maquinas","gimnasio_completo"],
    difficulty: "principiante",
    type: "hipertrofia",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Wide-Grip_Lat_Pulldown/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Wide-Grip_Lat_Pulldown/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Wide-Grip_Lat_Pulldown/1.jpg"],
    force: "Tirón",
    mechanic: "Compuesto",
    common_mistakes: [],
    tips: [],
    recommended_sets: 4,
    recommended_reps: "10-12",
    recommended_rest_seconds: 90,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "e14",
    name: "Barbell Deadlift",
    slug: "barbell-deadlift",
    description: "Pull movement, compound.",
    instructions: ["Stand hip-width with the bar over mid-foot.","Hinge down and grip the bar with a flat back and proud chest.","Push the floor away, extending hips and knees together.","Lower the bar under control, spine neutral."],
    main_muscle: "espalda",
    secondary_muscles: ["piernas","gluteos"],
    equipment: ["barras","gimnasio_completo"],
    difficulty: "avanzado",
    type: "fuerza",
    image_url: "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Deadlift/0.jpg",
    images: ["https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Deadlift/0.jpg","https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/Barbell_Deadlift/1.jpg"],
    force: "Tirón",
    mechanic: "Compuesto",
    common_mistakes: [],
    tips: [],
    recommended_sets: 4,
    recommended_reps: "5-8",
    recommended_rest_seconds: 180,
    alternatives: [],
    created_at: "2026-01-01T00:00:00Z",
  }

];

export const mockRoutine: RoutineRow = {
  id: "r1",
  user_id: "u1",
  name: "Push Pull Legs — Tone",
  goal: "push_pull_legs",
  days_per_week: 4,
  is_active: true,
  created_at: "2026-06-01T00:00:00Z",
  updated_at: "2026-06-20T00:00:00Z",
};

function re(
  id: string,
  dayId: string,
  exIndex: number,
  sets: number,
  reps: string,
  weight: number | null,
  rest: number,
  order: number
): RoutineExerciseRow & { exercise: ExerciseRow } {
  const exercise = mockExercises[exIndex];
  return {
    id,
    routine_day_id: dayId,
    exercise_id: exercise.id,
    sets,
    reps,
    suggested_weight_kg: weight,
    rest_seconds: rest,
    notes: null,
    order_index: order,
    exercise,
  };
}

export const mockRoutineDays: (RoutineDayRow & {
  exercises: (RoutineExerciseRow & { exercise: ExerciseRow })[];
})[] = [
  {
    id: "d1", routine_id: "r1", day_name: "Monday", day_order: 1,
    focus: "Push — chest, shoulders, triceps",
    exercises: [
      re("re1", "d1", 0, 4, "6-10", 42.5, 120, 0),
      re("re2", "d1", 1, 4, "6-10", 30, 120, 1),
      re("re3", "d1", 2, 3, "10-12", 25, 75, 2),
      re("re1b", "d1", 11, 4, "8-12", 22, 90, 3),
      re("re1c", "d1", 10, 3, "10-15", null, 60, 4),
    ],
  },
  {
    id: "d2", routine_id: "r1", day_name: "Wednesday", day_order: 2,
    focus: "Pull — back, biceps",
    exercises: [
      re("re4", "d2", 3, 4, "6-10", null, 120, 0),
      re("re5", "d2", 4, 4, "8-12", 40, 90, 1),
      re("re6", "d2", 5, 3, "10-12", 15, 75, 2),
      re("re2b", "d2", 12, 4, "8-12", 45, 90, 3),
      re("re2c", "d2", 9, 3, "12-15", 12, 60, 4),
    ],
  },
  {
    id: "d3", routine_id: "r1", day_name: "Friday", day_order: 3,
    focus: "Legs & glutes",
    exercises: [
      re("re7", "d3", 6, 4, "6-10", 60, 150, 0),
      re("re8", "d3", 7, 4, "8-12", 55, 120, 1),
      re("re9", "d3", 8, 4, "10-15", 50, 90, 2),
      re("re3b", "d3", 9, 3, "12-15", 40, 75, 3),
      re("re3c", "d3", 10, 3, "12-15", null, 60, 4),
    ],
  },
  {
    id: "d4", routine_id: "r1", day_name: "Saturday", day_order: 4,
    focus: "Core & accessories",
    exercises: [
      re("re10", "d4", 9, 3, "10-12", 12, 75, 0),
      re("re11", "d4", 10, 3, "30-60 seg", null, 45, 1),
      re("re4b", "d4", 11, 3, "10-12", 20, 60, 2),
      re("re4c", "d4", 12, 3, "10-12", 40, 75, 3),
    ],
  },
];

export const mockSessions: WorkoutSessionRow[] = [
  { id: "s1", user_id: "u1", routine_id: "r1", started_at: "2026-06-29T18:02:00Z", ended_at: "2026-06-29T19:01:00Z", duration_minutes: 59, total_volume_kg: 3120, total_sets: 16, total_reps: 142, notes: null },
  { id: "s2", user_id: "u1", routine_id: "r1", started_at: "2026-06-27T17:40:00Z", ended_at: "2026-06-27T18:35:00Z", duration_minutes: 55, total_volume_kg: 2890, total_sets: 16, total_reps: 138, notes: null },
  { id: "s3", user_id: "u1", routine_id: "r1", started_at: "2026-06-25T18:10:00Z", ended_at: "2026-06-25T19:05:00Z", duration_minutes: 55, total_volume_kg: 2640, total_sets: 14, total_reps: 120, notes: null },
  { id: "s4", user_id: "u1", routine_id: "r1", started_at: "2026-06-23T18:00:00Z", ended_at: "2026-06-23T18:58:00Z", duration_minutes: 58, total_volume_kg: 3010, total_sets: 16, total_reps: 140, notes: null },
];

export const weeklyVolume = [
  { week: "Sem 1", volumen: 9800 },
  { week: "Sem 2", volumen: 10650 },
  { week: "Sem 3", volumen: 11200 },
  { week: "Sem 4", volumen: 11660 },
];

export const bodyWeightTrend = [
  { date: "1 jun", peso: 65.4 },
  { date: "8 jun", peso: 65.0 },
  { date: "15 jun", peso: 64.6 },
  { date: "22 jun", peso: 64.4 },
  { date: "29 jun", peso: 64.2 },
];

export const mockBodyMetrics: BodyMetricRow[] = [
  { id: "b1", user_id: "u1", weight_kg: 64.2, height_cm: 165, waist_cm: 71, chest_cm: 89, arm_cm: 28, leg_cm: 55, hip_cm: 96, progress_photo_url: null, notes: null, recorded_at: "2026-06-29T08:00:00Z" },
  { id: "b2", user_id: "u1", weight_kg: 64.6, height_cm: 165, waist_cm: 71.5, chest_cm: 88.5, arm_cm: 27.8, leg_cm: 54.8, hip_cm: 96.2, progress_photo_url: null, notes: null, recorded_at: "2026-06-15T08:00:00Z" },
  { id: "b3", user_id: "u1", weight_kg: 65.4, height_cm: 165, waist_cm: 73, chest_cm: 88, arm_cm: 27.5, leg_cm: 54.5, hip_cm: 97, progress_photo_url: null, notes: null, recorded_at: "2026-06-01T08:00:00Z" },
];

export const mockNutritionToday: NutritionLogRow[] = [
  { id: "n1", user_id: "u1", meal_name: "Oats with fruit & protein", calories: 420, protein_g: 32, carbs_g: 52, fats_g: 9, water_ml: 500, notes: null, logged_at: "2026-06-30T08:30:00Z" },
  { id: "n2", user_id: "u1", meal_name: "Chicken, rice & veggies", calories: 610, protein_g: 48, carbs_g: 65, fats_g: 14, water_ml: 500, notes: null, logged_at: "2026-06-30T13:15:00Z" },
  { id: "n3", user_id: "u1", meal_name: "Greek yogurt & walnuts", calories: 240, protein_g: 18, carbs_g: 14, fats_g: 12, water_ml: 250, notes: null, logged_at: "2026-06-30T17:00:00Z" },
];

export const nutritionGoal = { calories: 2100, protein_g: 140, carbs_g: 220, fats_g: 65, water_ml: 2500 };

export const consistencyCalendar = [
  [1, 0, 1, 0, 1, 0, 0],
  [1, 0, 1, 0, 1, 0, 1],
  [0, 1, 0, 1, 0, 1, 0],
  [1, 0, 1, 0, 1, 0, 0],
  [1, 0, 1, 0, 1, 0, 1],
  [1, 0, 1, 0, 1, 0, 0],
  [1, 0, 0, 0, 0, 0, 0],
];
